"""Create stock_quotes table

Revision ID: a7ce5a70f815
Revises: 
Create Date: 2026-01-27 08:46:03.065482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7ce5a70f815'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_quotes_symbol'), ['symbol'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_quotes_symbol'))

    op.drop_table('stock_quotes')
    # ### end Alembic commands ###
